### ISSUE TITLE
Unable to play videos

### ISSUE THREAD

**Issue by tbob18** [Trellmor/jellyfin-mpc-shim#2]
Connected to MPC & Jellyfin

Error in log after attempting to cast:

2024-03-07 20:39:02.415 -06:00 [FTL] JellyfinMPCShim.MpcClient HandlePlay failed
System.Exception: MediaSource doesn't support direct stream
   at JellyfinMPCShim.JellyfinClient.GetPlaybackUrl(Guid itemId, MediaSourceInfo mediaSource) in N:\git\jellyfin-mpc-shim\src\JellyfinMPCShim\JellyfinClient.cs:line 174
   at JellyfinMPCShim.Video.GetPlaybackUrl() in N:\git\jellyfin-mpc-shim\src\JellyfinMPCShim\Video.cs:line 36
   at JellyfinMPCShim.MpcClient.PlayMedia(Media media, Int64 startPosition, Boolean startPaused) in N:\git\jellyfin-mpc-shim\src\JellyfinMPCShim\MpcClient.cs:line 105
   at JellyfinMPCShim.MpcClient.HandlePlay(JellyfinWebsockeMessage`1 message) in N:\git\jellyfin-mpc-shim\src\JellyfinMPCShim\MpcClient.cs:line 96
   at JellyfinMPCShim.JellyfinClient.HandleWebsockeMessage(ResponseMessage info, CancellationToken cancellationToken) in N:\git\jellyfin-mpc-shim\src\JellyfinMPCShim\JellyfinClient.cs:line 286

**Comment by Trellmor** [comment]
jellyfin-mpc-shim currently only supports direct streams. Looks like your jellyfin instance doesn't allow direct stream, or the media you selected can't be direct streamed.

I'll try to implement transcoded streams in the future, but it might take me a while to get around to it.

**Comment by tbob18** [comment]
> jellyfin-mpc-shim currently only supports direct streams. Looks like your jellyfin instance doesn't allow direct stream, or the media you selected can't be direct streamed.
> 
> I'll try to implement transcoded streams in the future, but it might take me a while to get around to it.

Hmm, I have transcoding completely disabled in jellyfin. I have the media folders mapped to as drive letters over the network. I had been using the a tampermoney/powershell method and while it works I was looking for something a bit more elegant with proper playback tracking.

**Comment by Trellmor** [comment]
It might get converted into a different container format on the fly. Can you share the mediainfo from jellyfin for the media you tried? Remove file names as necessary :)
